# Generated by Django 4.0 on 2022-01-02 11:08

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ips',
            fields=[
                ('IpID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('IpAddress', models.CharField(max_length=200)),
                ('SubNetID', models.CharField(default='', max_length=200)),
                ('ReserveName', models.CharField(default='', max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='subnet',
            fields=[
                ('SubnetID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('SubnetName', models.CharField(max_length=200, unique=True)),
                ('SubnetMask', models.CharField(max_length=200)),
                ('Networkip', models.CharField(max_length=200)),
                ('CIDR', models.CharField(max_length=2000)),
            ],
        ),
        migrations.CreateModel(
            name='vlan',
            fields=[
                ('VlanID', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('VlanName', models.CharField(max_length=200)),
                ('SubnetID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlanmgt.subnet', unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='subnet',
            name='Vlan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='vlanmgt.vlan', unique=True),
        ),
    ]
