# Generated by Django 4.0 on 2022-01-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vlanmgt', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vlan',
            name='VlanName',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
